# Default values for omar-stager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

fullnameOverride: omar-stager

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  hostname: omar-dev.ossim.io

  omarDb:
    name: null
    host: null
    user: null
    password: null
    port: null

  ingress:
    class: nginx
    enabled: true
    annotations: {}

  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true

  createHpa: true
  createPVs: true

  useSpringConfigServer: false

  deployment:
    annotations: {}

  serviceAccount:
    enabled: false
    annotations: {}
    # name:

  envVars: {}

  volumes:
    ossim-data:
      type: nfs
      nfsServer: null
      nfsMountPoint: null
      accessModes:
        - ReadWriteMany
      size: 1

volumeNames:
  - ossim-data

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 300m
    memory: 500Mi

image:
  name: omar-stager
  tag: null
  pullPolicy: IfNotPresent

ingress:
  enabled:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  class: # defaults to nginx if not set

ingressPath: /omar-stager
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  path: /omar-stager/actuator/health

terminationGracePeriodSeconds: 30

envVars:
  SPRING_CLOUD_DISCOVERY_ENABLED: false
  SPRING_CLOUD_CONFIG_ENABLED: false
  BUCKETS: o2-test-data

configmaps: {}

extraInitContainers: []

sideCars: []

deployment:
  annotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  enabled: null
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and enabled is true, a name is generated using the fullname template
  # name:

# Error writing for stager
errorsTable: true
slackErrors: false
slackWebhook: null
slackMessagePrefix: "<!here> `omar-stager` hit an error.  :emergency-alarm:"
