apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.fullnameOverride }}"
  labels:
    app: "{{ .Values.fullnameOverride }}"
data:
  application.yaml: |-
    environments:
      production:
        dataSource:
          url: ${omarDb.url}
          dbCreate: update
    omarDb:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      driver: org.postgresql.Driver
      host:  {{ .Values.global.omarDb.host }}
      name: {{ .Values.global.omarDb.name }}
      username: {{ .Values.global.omarDb.user }}
      password: {{ .Values.global.omarDb.password }}
      port: {{ .Values.global.omarDb.port }}
      url: jdbc:postgresql://${omarDb.host}:${omarDb.port}/${omarDb.name}
    grails:
      serverURL: {{ .Values.global.hostname}}${server.contextPath}

    server:
      servlet:
        context-path: {{ .Values.ingressPath }}
      contextPath: ${server.servlet.context-path}

    stager:
      errors:
        table:
          enabled: {{ .Values.errorsTable }}
        slack:
          enabled: {{ .Values.errorsSlack }}
          webhook: {{ .Values.slackWebhook | quote }}
          message: {{ .Values.slackMessage | quote }}
