apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-stager-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-stager-app
  uid: dcc709b7-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '9377772'
  generation: 718
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-stager-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-stager-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-stager-app@sha256:fa4af0855db9ccaed8c9d8648cfeff028dd158b18eb98073d2de8593db1a9596
    - type: ConfigChange
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-stager-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-stager-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-stager
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-stager-app
          image: >-
            172.30.181.173:5000/o2/omar-stager-app@sha256:fa4af0855db9ccaed8c9d8648cfeff028dd158b18eb98073d2de8593db1a9596
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: OSSIM_PREFS_FILE
              value: /usr/share/ossim/ossim-site-preferences
            - name: OSSIM_INSTALL_PREFIX
              value: /usr
            - name: OSSIM_DATA
              value: /data
            - name: BUCKETS
              value: o2-test-data
          resources:
            limits:
              memory: 4Gi
          volumeMounts:
            - name: volume-stager
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 704
  observedGeneration: 718
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-stager-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-11-27T21:08:15Z'
      lastTransitionTime: '2017-11-27T21:08:15Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-12-06T17:30:52Z'
      lastTransitionTime: '2017-12-06T17:30:49Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-stager-app-704" successfully rolled out
  readyReplicas: 1
